<?php

namespace Payutc\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Création de la table t_notification_not
 */
class Version20140607212315 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // Dans GCM le token peut faire jusqu'à 4ko ! Pour l'instant on met un varchar(255)
        // à modifier en cas de besoin
        $this->addSql("CREATE TABLE IF NOT EXISTS `t_notification_not` (
          `not_id` int(11) unsigned NOT NULL AUTO_INCREMENT,
          `not_type` varchar(40) COLLATE utf8_general_ci NOT NULL COMMENT 'Type d''appareil',
          `not_token` varchar(255) NOT NULL COMMENT 'Token spécifique à l''appareil',
          `not_user` int(11) unsigned NOT NULL COMMENT 'ID de l''utilisateur',
          PRIMARY KEY (`not_id`)
        ) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci COMMENT='Appareils à notifier';");
        $this->addSql("ALTER TABLE t_notification_not ADD CONSTRAINT `t_notification_not_ibfk_1` FOREIGN KEY (`not_user`) REFERENCES `ts_user_usr` (`usr_id`);");
        $this->addSql("ALTER TABLE t_notification_not ADD UNIQUE `t_notification_not_unique1` (not_type, not_token, not_user);");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->addSql("DROP TABLE t_notification_not;");
    }
}
